name: Application CI
on: [push, pull_request]
jobs:
  pipeline:
    name: letslink pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    env:
      NODE_VERSION: 16.17.0
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Install node.js packages
        run: npm install
      - name: 'E2E: Package'
        run: npm run ci:e2e:package
      - name: 'E2E: Prepare'
        run: npm run ci:e2e:prepare
      - name: 'E2E: Run'
        run: |
          google-chrome --version
          which google-chrome
          sudo apt update
          sudo apt install -y unzip xvfb libxi6 libgconf-2-4 webdriver-manager
          wget https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chown root:root /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          chromedriver -v
          wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.5.0/selenium-server-4.5.0.jar
          mv selenium-server-4.5.0.jar selenium-server-standalone.jar
          wget http://www.java2s.com/Code/JarDownload/testng/testng-6.8.7.jar.zip
          unzip testng-6.8.7.jar.zip
          xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone.jar
          webdriver-manager start
          npm run ci:e2e:run
      - name: 'E2E: Teardown'
        run: npm run ci:e2e:teardown
